# Generated by Django 5.1 on 2024-08-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_app', '0001_initial'),
        ('provider', '0002_remove_provider_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='internet',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
    ]
