# Generated by Django 5.1 on 2024-08-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('wallet', models.IntegerField(default=100000)),
                ('bought_internet', models.ManyToManyField(blank=True, to='internet_app.internet')),
            ],
        ),
    ]
